language: python
branches:
  only:
    - master
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.4-dev
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
install:
  - export PYTHONPATH=$PWD/p3270
script:
  - cd p3270/test
  - python test_p3270.py
